module.exports = function(grunt) {
  var config, name, nodeArgs, pkg, taskArray, taskName, tasks;
  pkg = grunt.file.readJSON('package.json');
  nodeArgs = [];
  if (grunt.option("verbose")) {
    nodeArgs.push("--verbose");
  }
  config = {
    nodemon: {
      dev: {
        options: {
          args: nodeArgs,
          env: {
            PORT: process.env.PORT || 3000
          },
          ext: 'js,html'
        },
        script: 'app.js'
      }
    },
    watch:{
			options:{livereload:true},
			files:['public/**'],
			tasks:[]
		},
  };
  tasks = {
    "default": ['nodemon','watch']
  };
  grunt.initConfig(config);
  for (name in pkg.devDependencies) {
    if (name.slice(0, 6) === 'grunt-' && name !== 'grunt-vtex') {
      grunt.loadNpmTasks(name);
    }
  }
  for (taskName in tasks) {
    taskArray = tasks[taskName];
    grunt.registerTask(taskName, taskArray);
  }
  return console.log(">>>>>>>>>>>>>>>>>>>>>>> gruntfile");
};

// ---
// generated by coffee-script 1.9.2

// module.exports = function(grunt) {
//
//     grunt.initConfig({
//         pkg: grunt.file.readJSON('package.json'),
//         nodemon: {
//             dev: {
//                 script: 'app.js',
//                 env: {
//                     PORT: '3000'
//                 },
//                 options: {
//                     args: ['dev'],
//                     nodeArgs: ['--debug'],
//                     callback: function (nodemon) {
//                         nodemon.on('log', function (event) {
//                             console.log(event.colour);
//                         });
//                     }
//                 }
//             }
//             // livereload  : {
//             //     options   : {
//             //         base    : 'public',
//             //     },
//             //     files     : ['public/**/*']
//             // },
//             // watch: {
//             //     somecss: {
//             //         files: '**/*.css',
//             //         tasks: ['copy:somecss']
//             //     },
//             //     js: {
//             //         files: '**/*.js',
//             //         tasks: ['concat']
//             //     }
//             // }
// 		}});
//
// 	    // grunt.loadNpmTasks('grunt-livereload');
//         grunt.loadNpmTasks('grunt-nodemon');
//         // grunt.loadNpmTasks('grunt-contrib-watch');
//
//         // grunt.registerTask('default', ['livereload']);
//         grunt.registerTask('default', ['nodemon']);
//
// 	};
